---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-app
  labels:
    app: zomato-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato-app
  template:
    metadata:
      labels:
        app: zomato-app
    spec:
      containers:
      - name: zomato-container
        image: 471024348059.dkr.ecr.us-east-1.amazonaws.com/zomato:latest
        ports:
        - containerPort: 3000
...
